const translate = {
  'id': {
    'Tentang': 'Tentang',
    'Kemampuan': 'Kemampuan',
    'Pengalaman': 'Pengalaman',
    'Projek': 'Projek',
    'Kontak': 'Kontak',
    '_halo': 'Halo semua, salam kenal.',
    'Seorang': 'Seorang',
    '_bio': 'tertarik dengan desain antarmuka interaktif dan pengoptimalan website dan aplikasi mobile. Saat ini fokus belajar',
    'Tentang Aku': 'Tentang Aku',
    'Cerita Tentang Aku': 'Cerita Tentang Aku',
    '_cerita1': 'Namaku Fandi dari Indonesia. Suka pemrograman dan desain.',
    '_cerita2': 'Aku mengenal pemrograman pada tahun 2013 ketika bersekolah di salah satu SMK. Kenapa aku suka pemrograman? Itu karena menurutku pemrograman seperti permainan logika. Kemudian aku mulai menyukai dengan pemrograman web saat magang di sebuah software house.',
    '_cerita3': 'Seiring waktu, aku ditugaskan dalam sebuah projek untuk membuat web ujian online untuk sekolah. Setelah lulus sekolah, aku melanjutkan kuliah di universitas dan mengambil jurusan informatika. Disitulah aku mengenal Artificial Intelligence, Machine Learning, dan Data Mining. Menurutku itu ilmu yang sulit, tapi menarik.',
    '_cerita4': 'Sebelum lulus, aku sudah bekerja di sebuah lembaga yang mengembangkan aplikasi dan media inovasi yang disruptif. Sampai saat ini, aku membantu pada bagian pengembangan frontend.',
    '_skill1': 'Beberapa teknologi yang telah dicoba',
    '_skill2': 'Kemampuan untuk mendukung pekerjaan',
    'Adaptif': 'Adaptif',
    'Kolaborasi': 'Kolaborasi',
    'Komunikasi': 'Komunikasi',
    'Problem Solving': 'Problem Solving',
    'Keingintahuan': 'Keingintahuan',
    'Kursus': 'Kursus',
    'Kerja Full-time': 'Kerja Full-time',
    'Magang': 'Magang',
    'Juni 2022 - Juli 2022': 'Juni 2022 - Juli 2022',
    'Juli 2020 - Saat ini': 'Juli 2020 - Saat ini',
    'Juli 2019 - Juli 2020': 'Juli 2019 - Juli 2020',
    'Januari 2015 - Juni 2015': 'Januari 2015 - Juni 2015',
    'Yang pernah dibuat': 'Yang pernah dibuat',
    'Tahun': 'Tahun',
    'Nama': 'Nama',
    'Asosiasi': 'Asosiasi',
    'Teknologi': 'Teknologi',
    'Aplikasi Catatan': 'Aplikasi Catatan',
    'Aplikasi Rak Buku': 'Aplikasi Rak Buku',
    'Landing Page Interaktif & Responsif': 'Landing Page Interaktif & Responsif',
    'Website Profil': 'Website Profil',
    'Sistem Automatic Text Summarization': 'Sistem Automatic Text Summarization',
    'Backend Sistem ATS': 'Backend Sistem ATS',
    'Terima Kasih': 'Terima Kasih',
    '_contactme': 'Jika kamu memiliki pertanyaan, emailku selalu terbuka untuk siapapun. Kita dapat berdiskusi dan bisa jadi berkolaborasi.',
    'Hubungi Aku': 'Hubungi Aku',
    'Di desain dan dibuat oleh': 'Di desain dan dibuat oleh',
    'Inspirasi dari': 'Inspirasi dari',
  },
  'en': {
    'Tentang': 'About',
    'Kemampuan': 'Skill',
    'Pengalaman': 'Experience',
    'Projek': 'Project',
    'Kontak': 'Contact',
    '_halo': 'Hello everyone, nice to meet you.',
    'Seorang': 'A',
    '_bio': 'interested in interactive interface design and optimization of websites and mobile applications. Currently focusing on learning',
    'Tentang Aku': 'About Me',
    'Cerita Tentang Aku': 'Story About Me',
    '_cerita1': 'My name is Fandi from Indonesia. Love programming and design.',
    '_cerita2': 'I got to know programming in 2013 when I was in a vocational school. Why do I like programming? That\'s because I think programming is like a logic game. Then I started liking web programming while doing an internship at a software house.',
    '_cerita3': 'Over time, I was assigned to a project to create an online exam web for schools. After graduating from school, I continued my studies at university and majored in informatics. That\'s where I got to know Artificial Intelligence, Machine Learning, and Data Mining. I think it\'s a difficult science, but interesting.',
    '_cerita4': 'Before graduating, I worked at an institution that developed disruptive innovation applications and media. Until now, I was helping on the frontend development part.',
    '_skill1': 'Some of the technologies that have been tried',
    '_skill2': 'Ability to support work',
    'Adaptif': 'Adaptive',
    'Kolaborasi': 'Collaboration',
    'Komunikasi': 'Communication',
    'Problem Solving': 'Problem Solving',
    'Keingintahuan': 'Curious',
    'Kursus': 'Course',
    'Kerja Full-time': 'Full-time Work',
    'Magang': 'Intern',
    'Juni 2022 - Juli 2022': 'June 2022 - July 2022',
    'Juli 2020 - Saat ini': 'July 2020 - Now',
    'Juli 2019 - Juli 2020': 'July 2019 - July 2020',
    'Januari 2015 - Juni 2015': 'January 2015 - June 2015',
    'Yang pernah dibuat': 'Which has been made',
    'Tahun': 'Year',
    'Nama': 'Name',
    'Asosiasi': 'Association',
    'Teknologi': 'Technologies',
    'Aplikasi Catatan': 'Note App',
    'Aplikasi Rak Buku': 'Bookshelf App',
    'Landing Page Interaktif & Responsif': 'Interactive & Responsive Landing Page',
    'Website Profil': 'Website Profile',
    'Sistem Automatic Text Summarization': 'Automatic Text Summarization System',
    'Backend Sistem ATS': 'Backend ATS System',
    'Terima Kasih': 'Thank You',
    '_contactme': 'If you have any questions, my email is always open to anyone. We can discuss and we can collaborate.',
    'Hubungi Aku': 'Contact Me',
    'Di desain dan dibuat oleh': 'Designed and build by',
    'Inspirasi dari': 'Inspiration from',
  },
}

export {translate};